name: appli-web
services:
  master:
    image: alpine:latest
    container_name: master01
    hostname: master01
    stdin_open: true
    tty: true
    command : >
      /bin/sh -c "apk update 
      &&  apk add ansible openssh-server openssh
      && /bin/sh"
    volumes:
      - ansible_vol:/var/ans
      - ./files/:/files/
  webserver:
    links:
      - master
    image: takeyamajp/ubuntu-sshd
    container_name: webserver
    hostname: webserver
    stdin_open: true
    tty: true
    environment:
      ROOT_PASSWORD: toor
    command : "/usr/sbin/sshd -D"
    expose: 
      - 22
    ports:
      - 8042:80
    volumes:
     - ansible_vol:/var/ans
  dbserver:
    links:
      - master
    image: takeyamajp/ubuntu-sshd
    container_name: dbserver
    hostname: dbserver
    stdin_open: true
    tty: true
    environment:
      ROOT_PASSWORD: toor
    command : "/usr/sbin/sshd -D"
    expose: 
      - 22
    ports:
      - 3306:3306
    volumes:
     - ansible_vol:/var/ans
volumes:
  ansible_vol:
